# GitHub Actions workflow
# https://help.github.com/en/actions/reference

name: Build

on:
  push:
    branches:
      - master
    tags:
      - release/*
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Authenticate Docker Hub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN

      - name: Build Image
        run: >
          docker build
          --tag sharpjs/psql-mssql:$(date +%Y.%m.%d)
          --tag sharpjs/psql-mssql:latest
          --label git.commit=${{ github.sha }}
          .
          
      - name: Push Image
        run: docker push sharpjs/psql-mssql:latest
